version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
    - 3000:3000
    volumes:
    - ./src:/app/src
    depends_on:
    - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
       POSTGRES_PASSWORD: postgres

  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: iamhuraira429@gmail.com
      PGADMIN_DEFAULT_PASSWORD: huraira786